{
 "title": "NGINX exporter",
 "description": "NGINX Prometheus exporter dashboard with additional metrics from cAdvisor",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"lancache-docker-compose-monolithic-1\"}[$__rate_interval])",
     "legendFormat": "Recieved bytes"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{name=\"lancache-docker-compose-monolithic-1\"}[$__rate_interval])",
     "legendFormat": "Transmitted bytes"
    }
   ]
  }
 ]
}